/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "header.h"
#include <string.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_ICON_ADD (GUI_ID_USER + 0x2C)
#define ID_ICON_DEL (GUI_ID_USER + 0x2D)
#define ID_TREE_0     (GUI_ID_USER + 0x2E)

#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_A     (GUI_ID_USER + 0x02)
#define ID_BUTTON_B     (GUI_ID_USER + 0x03)
#define ID_BUTTON_C     (GUI_ID_USER + 0x04)
#define ID_BUTTON_D     (GUI_ID_USER + 0x05)
#define ID_BUTTON_E     (GUI_ID_USER + 0x06)
#define ID_BUTTON_F     (GUI_ID_USER + 0x07)
#define ID_BUTTON_G     (GUI_ID_USER + 0x08)
#define ID_BUTTON_H     (GUI_ID_USER + 0x09)
#define ID_BUTTON_I     (GUI_ID_USER + 0x0A)
#define ID_BUTTON_J     (GUI_ID_USER + 0x0B)
#define ID_BUTTON_K     (GUI_ID_USER + 0x0C)
#define ID_BUTTON_L     (GUI_ID_USER + 0x0D)
#define ID_BUTTON_M     (GUI_ID_USER + 0x0E)
#define ID_BUTTON_N     (GUI_ID_USER + 0x0F)
#define ID_BUTTON_O     (GUI_ID_USER + 0x10)
#define ID_BUTTON_P     (GUI_ID_USER + 0x11)
#define ID_BUTTON_Q     (GUI_ID_USER + 0x12)
#define ID_BUTTON_R     (GUI_ID_USER + 0x13)
#define ID_BUTTON_S     (GUI_ID_USER + 0x14)
#define ID_BUTTON_T     (GUI_ID_USER + 0x15)
#define ID_BUTTON_U     (GUI_ID_USER + 0x16)
#define ID_BUTTON_V     (GUI_ID_USER + 0x17)
#define ID_BUTTON_W     (GUI_ID_USER + 0x18)
#define ID_BUTTON_X     (GUI_ID_USER + 0x19)
#define ID_BUTTON_Y     (GUI_ID_USER + 0x1A)
#define ID_BUTTON_Z     (GUI_ID_USER + 0x1B)
#define ID_BUTTON_0     (GUI_ID_USER + 0x1C)
#define ID_BUTTON_1     (GUI_ID_USER + 0x1D)
#define ID_BUTTON_2     (GUI_ID_USER + 0x1E)
#define ID_BUTTON_3     (GUI_ID_USER + 0x1F)
#define ID_BUTTON_4     (GUI_ID_USER + 0x20)
#define ID_BUTTON_5     (GUI_ID_USER + 0x21)
#define ID_BUTTON_6     (GUI_ID_USER + 0x22)
#define ID_BUTTON_7     (GUI_ID_USER + 0x23)
#define ID_BUTTON_8     (GUI_ID_USER + 0x24)
#define ID_BUTTON_9     (GUI_ID_USER + 0x25)

#define ID_BUTTON_point     (GUI_ID_USER + 0x26)
#define ID_BUTTON__         (GUI_ID_USER + 0x27)
#define ID_BUTTON_ENTER     (GUI_ID_USER + 0x28)
#define ID_BUTTON_SHIFT     (GUI_ID_USER + 0x29)
#define ID_BUTTON_DEL       (GUI_ID_USER + 0x2A)

#define ID_EDIT_0						(GUI_ID_USER+0x2B)

uint8_t shift;
extern void _readDIR(TCHAR *pPath);
BUTTON_SKINFLEX_PROPS SHIFT_PRES;
	
WM_HWIN hWin_KEY;
extern WM_HWIN hWin_SD;
extern TREEVIEW_ITEM_Handle hNode;
	TREEVIEW_Handle hTree;

static const GUI_WIDGET_CREATE_INFO _aBUTTON_KEY[] = {
  { FRAMEWIN_CreateIndirect, NULL, ID_FRAMEWIN_0, 35, 70, 315, 170, WM_CF_SHOW, 0x64, 0 },
  { EDIT_CreateIndirect, NULL, ID_EDIT_0, 0,0,300,25,0,40,0},
	
	{ BUTTON_CreateIndirect, "1", ID_BUTTON_1, 10, 30, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "2", ID_BUTTON_2, 35, 30, 25, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_3, 60, 30, 25, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_4, 85, 30, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "5", ID_BUTTON_5, 110, 30, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "6", ID_BUTTON_6, 135, 30, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "7", ID_BUTTON_7, 160, 30, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "8", ID_BUTTON_8, 185, 30, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "9", ID_BUTTON_9, 210, 30, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "0", ID_BUTTON_0, 235, 30, 25, 25, 0, 0x0, 0 },

	{ BUTTON_CreateIndirect, "Q", ID_BUTTON_Q, 20, 55, 25, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "W", ID_BUTTON_W, 45, 55, 25, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "E", ID_BUTTON_E, 70, 55, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "R", ID_BUTTON_R, 95, 55, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "T", ID_BUTTON_T, 120, 55, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Y", ID_BUTTON_Y, 145, 55, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "U", ID_BUTTON_U, 170, 55, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "I", ID_BUTTON_I, 195, 55, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "O", ID_BUTTON_O, 220, 55, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "P", ID_BUTTON_P, 245, 55, 25, 25, 0, 0x0, 0 },
  
	{ BUTTON_CreateIndirect, "A", ID_BUTTON_A, 30, 80, 25, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "S", ID_BUTTON_S, 55, 80, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "D", ID_BUTTON_D, 80, 80, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "F", ID_BUTTON_F, 105, 80, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "G", ID_BUTTON_G, 130, 80, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "H", ID_BUTTON_H, 155, 80, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "J", ID_BUTTON_J, 180, 80, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "K", ID_BUTTON_K, 205, 80, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "L", ID_BUTTON_L, 230, 80, 25, 25, 0, 0x0, 0 },
  
	{ BUTTON_CreateIndirect, "Z", ID_BUTTON_Z, 40, 105, 25, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "X", ID_BUTTON_X, 65, 105, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "C", ID_BUTTON_C, 90, 105, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "V", ID_BUTTON_V, 115, 105, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "B", ID_BUTTON_B, 140, 105, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "N", ID_BUTTON_N, 165, 105, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "M", ID_BUTTON_M, 190, 105, 25, 25, 0, 0x0, 0 },
	
	{ BUTTON_CreateIndirect, "_", ID_BUTTON__, 260, 30, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, ".", ID_BUTTON_point, 215, 105, 25, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "DEL", ID_BUTTON_DEL, 270, 55, 35, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "ENTER", ID_BUTTON_ENTER, 255, 80, 50, 40, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "SHIFT", ID_BUTTON_SHIFT, 0, 105, 40, 25, 0, 0x0, 0 },
	
	
};

int _cbButtonSkin(const WIDGET_ITEM_DRAW_INFO *pDrawItemInfo){
	#define RAD 4
	GUI_RECT Rect;
	switch(pDrawItemInfo->Cmd){
		case WIDGET_ITEM_DRAW_BACKGROUND:
			GUI_SetPenSize(1);
			Rect.x0=pDrawItemInfo->x0;
			Rect.x1=pDrawItemInfo->x1;
			Rect.y0=pDrawItemInfo->y0;
			Rect.y1=pDrawItemInfo->y1;
			GUI_SetColor(GUI_LIGHTRED);
			GUI_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RAD);
			GUI_DrawGradientV(Rect.x0+RAD, Rect.y0, Rect.x1-RAD, (Rect.y1-Rect.y0)/2,GUI_WHITE,GUI_LIGHTRED);
			GUI_SetColor(GUI_RED);
			GUI_DrawArc(Rect.x0 + RAD, Rect.y0 + RAD, RAD, RAD, 90, 180);
			GUI_DrawArc(Rect.x1 - RAD, Rect.y0 + RAD, RAD, RAD, 0, 90);
			GUI_DrawArc(Rect.x1 - RAD, Rect.y1 - RAD, RAD, RAD, 270, 359);
			GUI_DrawArc(Rect.x0 + RAD, Rect.y1 - RAD, RAD, RAD, 180, 270);
			GUI_DrawLine(Rect.x0 + RAD, Rect.y0, Rect.x1 - RAD, Rect.y0);
			GUI_DrawLine(Rect.x1, Rect.y0 + RAD, Rect.x1, Rect.y1 - RAD);
			GUI_DrawLine(Rect.x0 + RAD, Rect.y1, Rect.x1 - RAD, Rect.y1);
			GUI_DrawLine(Rect.x0, Rect.y0 + RAD, Rect.x0, Rect.y1 - RAD);


		break;
		default:
			return BUTTON_DrawSkinFlex(pDrawItemInfo);
		}
	return 0;
}


/*********************************************************************
*
*       _cbBUTTON_KEY
*/
static void _cbBUTTON_KEY(WM_MESSAGE * pMsg) {
  char unicode[80];
	TCHAR Buff[40];
	TCHAR *pBuff;
	TCHAR *pPath;
	char m;
	int     NCode;
  int     Id;
	
	ICONVIEW_Handle hIcon;
	EDIT_Handle hEdit;
	WM_HWIN hWin;
	BUTTON_Handle hButton;
 	
	switch (pMsg->MsgId) {
	case WM_DELETE:
		hWin=WM_GetParent(pMsg->hWin);
		hIcon=WM_GetDialogItem(hWin,ID_ICON_ADD);
		WM_EnableWindow(hIcon);
		hIcon=WM_GetDialogItem(hWin,ID_ICON_DEL);
		WM_EnableWindow(hIcon);
		pMsg->hWin=0;
		
	break;
	case WM_INIT_DIALOG:
		hWin = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hWin, 20);
    FRAMEWIN_SetMoveable(hWin, 1);
		FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT,0);
		WM_EnableMemdev(hWin);
		
		shift=0;
		hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
		EDIT_SetFont(hEdit, GUI_FONT_20_1);
		
	break;
	case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
		case ID_BUTTON_DEL:
		 switch(NCode){
			 case WM_NOTIFICATION_RELEASED:
					hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
					EDIT_GetText(hEdit, unicode, 40);
					GUI_UC_ConvertUTF82UC(unicode, 40,Buff,40);
					pBuff=wcstrchr(Buff,'\0');
					*(--pBuff)='\0';
					GUI_UC_ConvertUC2UTF8(Buff, 40,unicode, 40);
					EDIT_SetText(hEdit, unicode);
			 break; 
			}
		break;	
		case ID_BUTTON_ENTER:
		 switch(NCode){
			 case WM_NOTIFICATION_RELEASED:
					hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
					EDIT_GetText(hEdit, unicode, 40);
					GUI_UC_ConvertUTF82UC(unicode, 40,Buff,40);
					pPath=wcstrchr(Path,'\0');
					*pPath++='/';
					*pPath='\0';
					wcstrcat(Path,Buff);
					hWin=WM_GetParent(pMsg->hWin);
					hTree=WM_GetDialogItem(hWin,ID_TREE_0);
					hNode=TREEVIEW_GetSel(hTree);
					
					pPath=wcstrchr(Path,'\0');
					while((*pPath!='.')&&(*pPath!='/'))
						pPath--;
					
					if(*pPath=='.')
					{
						fresult=f_open (&fil,Path, FA_CREATE_NEW);
						if(fresult==FR_EXIST)
							{
								Message("Такой файл существует!",Msg_Err);
								while(*pPath!='/')
									pPath--;
								*pPath='\0';
							}	
						else if(fresult==FR_OK)
							{
								GUI_UC_ConvertUC2UTF8(Buff, 40,unicode, 40);
								hNode=TREEVIEW_InsertItem(hTree,TREEVIEW_ITEM_TYPE_LEAF,hNode,TREEVIEW_INSERT_BELOW,unicode/*finfo.fname*/);		
								GUI_EndDialog(pMsg->hWin,0);
								while(*pPath!='/')
									pPath--;
								*pPath='\0';
							}
					}
					else
					{
						fresult=f_mkdir(Path);
						if(fresult==FR_EXIST)
							{
								Message("Такой каталог существует!",Msg_Err);
								*pPath='\0';
							}	
						else if(fresult==FR_OK)
							{
								GUI_UC_ConvertUC2UTF8(Buff, 40,unicode, 40);
								hNode=TREEVIEW_InsertItem(hTree,TREEVIEW_ITEM_TYPE_NODE,hNode,TREEVIEW_INSERT_BELOW,unicode/*finfo.fname*/);
								GUI_EndDialog(pMsg->hWin,0);
								*pPath='\0';
							}
					}
					
			 break; 
			}
		break;	
		case ID_BUTTON_SHIFT: // Notifications sent by 'Button'
      hButton=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_SHIFT);
			switch(NCode) {
				case WM_NOTIFICATION_CLICKED:
				BUTTON_SetSkin(hButton, BUTTON_SKIN_FLEX);
				break;	
				case WM_NOTIFICATION_RELEASED:
																												//i=BUTTON_IsPressed(hButton);
				if(shift==0)
				{	BUTTON_SetSkin(hButton, _cbButtonSkin);
					shift=1;																					//BUTTON_SetPressed(hButton,0);
				}
				else
				{	BUTTON_SetSkin(hButton, BUTTON_SKIN_FLEX);
					shift=0;																						//BUTTON_SetPressed(hButton,0);
				}
				break;
      }
    break;
		case ID_BUTTON_point: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'.');	
			break;
      }
    break;
		case ID_BUTTON__: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'_');	
			break;
      }
    break;
		case ID_BUTTON_1: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'1');	
			break;
      }
    break;
		case ID_BUTTON_2: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'2');	
			break;
      }
    break;
		case ID_BUTTON_3: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'3');	
			break;
      }
    break;
		case ID_BUTTON_4: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'4');	
			break;
      }
    break;
		case ID_BUTTON_5: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'5');	
			break;
      }
    break;
		case ID_BUTTON_6: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'6');	
			break;
      }
    break;
		case ID_BUTTON_7: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'7');	
			break;
      }
    break;
		case ID_BUTTON_8: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'8');	
			break;
      }
    break;
		case ID_BUTTON_9: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'9');	
			break;
      }
    break;
		case ID_BUTTON_0: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				EDIT_AddKey(hEdit,'0');	
			break;
      }
    break;
		case ID_BUTTON_A: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='A';	
				else
					m='a';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
    case ID_BUTTON_B: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='B';	
				else
					m='b';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
    case ID_BUTTON_C: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='C';	
				else
					m='c';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
    case ID_BUTTON_D: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='D';	
				else
					m='d';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_E: // Notifications sent by 'Button'
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='E';	
				else
					m='e';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_F: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='F';	
				else
					m='f';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_G: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='G';	
				else
					m='g';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_H: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='H';	
				else
					m='h';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_I: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='I';	
				else
					m='i';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_J: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='J';	
				else
					m='j';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_K: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='K';	
				else
					m='k';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_L: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='L';	
				else
					m='l';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_M: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='M';	
				else
					m='m';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_N: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='N';	
				else
					m='n';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_O: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='O';	
				else
					m='o';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_P: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='P';	
				else
					m='p';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_Q: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='Q';	
				else
					m='q';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_R: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='R';	
				else
					m='r';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_S: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='S';	
				else
					m='s';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_T: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='T';	
				else
					m='t';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_U: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='U';	
				else
					m='u';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_V: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='V';	
				else
					m='v';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_W: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='W';	
				else
					m='w';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_X: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='X';	
				else
					m='x';
				EDIT_AddKey(hEdit,m);		
			break;
      }
    break;
		case ID_BUTTON_Y: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='Y';	
				else
					m='y';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;
		case ID_BUTTON_Z: 
     switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hEdit=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
				if(shift)
					m='Z';	
				else
					m='z';
				EDIT_AddKey(hEdit,m);	
			break;
      }
    break;		
		}
  break;
  default:
  WM_DefaultProc(pMsg);
  break;
  }
}

/*********************************************************************
*
*       CreateMENU
*/

WM_HWIN BUTTON_KEY(WM_HWIN hWin) {
	
	
	hWin_KEY= GUI_CreateDialogBox(_aBUTTON_KEY, GUI_COUNTOF(_aBUTTON_KEY), _cbBUTTON_KEY, hWin, 0, 0);
	return hWin_KEY;

}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
